name: Code Review
on:
  pull_request:
    branches:
      - main
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run code review
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          # ファイルの変更点を取得
          FILES=$(curl -H "Authorization: token $TOKEN" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files)

          # JSONエスケープ
          ESCAPED_FILES=$(echo "$FILES" | jq -c .)

          echo "fefe: $ESCAPED_FILES"

          # ファイルの変更点をAIに渡してレビューコメントを生成
          AI_RESPONSE=$(curl -X POST "https://models.inference.ai.azure.com/chat/completions" \
                              -H "Content-Type: application/json" \
                              -H "Authorization: Bearer $TOKEN" \
                              -d @- <<EOF
{
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "こんにちはと返して"
    }
  ],
  "model": "gpt-4o"
}
EOF
          )

          # AIのレスポンスを出力
          echo "AI Response: $AI_RESPONSE"

          # AIのレスポンスをコメントとしてプルリクエストに投稿
          curl -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d @- <<EOF
{
  "event": "COMMENT",
  "body": $AI_RESPONSE
}
EOF
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews