name: Code Review
on:
  pull_request:
    branches:
      - main
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run code review
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          # ファイルの変更点を取得
          FILES=$(curl -H "Authorization: token $TOKEN" \
                      -H "Accept: application/vnd.github.v3+json" \
                      https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files)

          # JSONエスケープ
          ESCAPED_FILES=$(echo "$FILES" | jq -R . | jq -s .)

          # ファイルの変更点をAIに渡してレビューコメントを生成 (ここでAIのAPIを使用)
          AI_RESPONSE=$(curl -X POST "https://api.example.com/review" \
                              -H "Content-Type: application/json" \
                              -d '{"files": '"$ESCAPED_FILES"'}')

          # AIのレスポンスをコメントとしてプルリクエストに投稿
          curl -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"event":"COMMENT","body":'"$AI_RESPONSE"'}' \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews
