name: Code Review
on:
  pull_request:
    branches:
      - main
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run code review
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          # Define the JSON payload using double quotes inside the JSON string to avoid conflicts with shell quoting
          JSON_PAYLOAD=$(cat <<EOF
          {
            "messages": [
              {
                "role": "system",
                "content": "You are a helpful assistant."
              },
              {
                "role": "user",
                "content": "What is the capital of France?"
              }
            ],
            "temperature": 1.0,
            "top_p": 1.0,
            "max_tokens": 1000,
            "model": "gpt-4o"
          }
EOF
          )

          # Send the API request and capture the AI's response
          AI_RESPONSE=$(curl -X POST "https://models.inference.ai.azure.com/chat/completions" \
                        -H "Content-Type: application/json" \
                        -H "Authorization: Bearer $TOKEN" \
                        -d "$JSON_PAYLOAD" | jq -r '.choices[0].message.content')

          # Post the AI response as a comment on the pull request
          curl -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"event":"COMMENT","body":'"$(echo "$AI_RESPONSE" | jq -R .)"}' \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews