name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "BTUPJK2"
          ICON_FIRST: "#000000"
          ICON_SECOND: "#001eff"
          BACKGROUND_FIRST: "#474747"
          BACKGROUND_SECOND: "#000000"
          LANG: "en"